GET http://localhost:8080
Content-Type: application/json

###
POST http://localhost:8080
Content-Type: application/json

{
  "body": "Hello, World!"
}

###
POST http://localhost:8080
Content-Type: application/json

{
  "body": "Hello, all!"
}

###
