name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to triggre manual jobs
        required: false
        default: ''
jobs:
  tests:
    name: java-${{ matrix.java }} tests
    if: github.event.inputs.trigger == ''
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.gradle
            ~/.docker
            ~/.m2/repository
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle', '**/pom.xml') }}
      - uses: actions/setup-node@v2
      - run: cd $GITHUB_WORKSPACE ; ./mvnw
  dependency-updates:
    if: contains(github.event.inputs.trigger, 'M')
      || startsWith(github.event.inputs.trigger, 'm')
    name: java-${{ matrix.java }} dependency-updates
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ 17 ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v3
      id: ci
      with:
        path: |
          ~/.npm
          ~/.node
          ~/.local
          ~/.gradle
          ~/.docker
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/*.gradle', '**/pom.xml') }}
    - run: cd $GITHUB_WORKSPACE ; ./mvnw versions:display-plugin-updates
    - run: cd $GITHUB_WORKSPACE ; ./mvnw versions:display-parent-updates
    - run: cd $GITHUB_WORKSPACE ; ./mvnw versions:display-property-updates
